### PR TITLE
WIP-Basic inpainting changes

### PR DESCRIPTION
**Pull request by isamu-isozaki**
Added inpainting. TODOs are

- [ ] Add script for testing inpainting given input image and mask
- [ ] Test above

I'll finish this up tomorrow

### CODE REVIEW

**Comment by isamu-isozaki** [comment]
Ah, sorry. Will test tomorrow and put the results here

**Comment by isamu-isozaki** [comment]
@patil-suraj Some results 
input:
segmented
output with prompt "a photo of a dog"
output_4
output_5
output_6
output_7

**Comment by patil-suraj** [comment]
great work @isamu-isozaki , merging the PR !

**Review by patil-suraj — APPROVED** [review]

**Comment by isamu-isozaki** [comment]
Thanks!

**Pull request merged**
