### PR TITLE
WIP: Simple FID

### PR DESCRIPTION
**Pull request by isamu-isozaki**
I tried adding the most simple fid first

### CODE REVIEW

**Comment by pcuenca** [comment]
Did you consider [clean-fid](https://pypi.org/project/clean-fid/)? It's used in other repos such as k-diffusion.

**Comment by patil-suraj** [comment]
Sorry to be late here. @isamu-isozaki Yes, let's add it as extra/optional dep.

**Comment by patil-suraj** [comment]
@isamu-isozaki Will go in this PR and the `clean-fid` dep and modify the script accordingly.

**Comment by isamu-isozaki** [comment]
@patil-suraj thanks! And sounds good

**Pull request merged**
