### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by patrickvonplaten**

### CODE REVIEW

**Review by isamu-isozaki — DISMISSED** [review]
LGTM! For reference, we get an import error which requires
 accelerate>=0.20.3

**Comment by isamu-isozaki** [comment]
Interesting now it's failing on 
```
import accelerate
```
with
```
[/usr/local/lib/python3.10/dist-packages/accelerate/utils/__init__.py](https://localhost:8080/#) in <module>
----> 1 from .constants import (
      2     MODEL_NAME,
      3     OPTIMIZER_NAME,
      4     RNG_STATE_NAME,
      5     SAFE_WEIGHTS_INDEX_NAME,

ImportError: cannot import name 'SAFE_WEIGHTS_INDEX_NAME' from 'accelerate.utils.constants' (/usr/local/lib/python3.10/dist-packages/accelerate/utils/constants.py)
```

**Comment by isamu-isozaki** [comment]
nvm fixed

**Review by isamu-isozaki — APPROVED** [review]

**Comment by lizelive** [comment]
can we merge this in?

**Pull request merged**
